[package]
name = "vmm"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2024"
license = "Apache-2.0"

[lib]
bench = false

[features]
default = []
tracing = ["log-instrument"]
gdb = ["arrayvec", "gdbstub", "gdbstub_arch"]

[dependencies]
acpi_tables = { path = "../acpi-tables" }
aes-gcm = { version = "0.10.1", default-features = false, features = ["aes"] }
arrayvec = { version = "0.7.6", optional = true }
aws-lc-rs = { version = "1.13.1", features = ["bindgen"] }
base64 = "0.22.1"
bincode = { version = "2.0.1", features = ["serde"] }
bitflags = "2.9.1"
crc64 = "2.0.0"
derive_more = { version = "2.0.1", default-features = false, features = ["from", "display"] }
displaydoc = "0.2.5"
event-manager = "0.4.1"
gdbstub = { version = "0.7.6", optional = true }
gdbstub_arch = { version = "0.3.2", optional = true }
kvm-bindings = { version = "0.13.0", features = ["fam-wrappers", "serde"] }
kvm-ioctls = "0.23.0"
libc = "0.2.174"
linux-loader = "0.13.0"
log = { version = "0.4.27", features = ["std", "serde"] }
log-instrument = { path = "../log-instrument", optional = true }
memfd = "0.6.3"
micro_http = { git = "https://github.com/firecracker-microvm/micro-http" }
semver = { version = "1.0.26", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive", "rc"] }
serde_json = "1.0.140"
slab = "0.4.10"
thiserror = "2.0.12"
timerfd = "1.5.0"
userfaultfd = "0.8.1"
utils = { path = "../utils" }
vhost = { version = "0.14.0", features = ["vhost-user-frontend"] }
vm-allocator = "0.1.3"
vm-memory = { version = "0.16.2", features = ["backend-mmap", "backend-bitmap"] }
vm-superio = "0.8.0"
vmm-sys-util = { version = "0.14.0", features = ["with-serde"] }
zerocopy = { version = "0.8.26" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
vm-fdt = "0.3.0"

[dev-dependencies]
criterion = { version = "0.6.0", default-features = false }
device_tree = "1.1.0"
itertools = "0.14.0"
proptest = { version = "1.7.0", default-features = false, features = ["std"] }

[[bench]]
name = "cpu_templates"
harness = false

[[bench]]
name = "queue"
harness = false

[[bench]]
name = "block_request"
harness = false

[[bench]]
name = "memory_access"
harness = false

[lints]
workspace = true
