[advisories]
# The `paste` dependency is transitively included via `gdbstub`.
# While the crate is archived/unmaintained, the author considers it feature-complete
# and functionally stable. gdbstub will be update once they migrate 
# to an alternative solution.
# See https://github.com/daniel5151/gdbstub/issues/168
ignore = ["RUSTSEC-2024-0436"]
